#!/usr/bin/env bash
set -x

# DO NOT EDIT THIS FILE BY HAND -- FILE IS SYNCHRONIZED REGULARLY

# Available environment variables
#
# REPOSITORY
# VERSION

# https://github.com/jenkinsci/docker/blob/master/update-official-library.sh
version-from-dockerfile() {
    grep VERSION: Dockerfile | sed -e 's/.*:-\(.*\)}/\1/'
}

if [[ -z $VERSION ]]; then
    VERSION=$(version-from-dockerfile)
fi

docker push "$REPOSITORY:$VERSION"
docker rmi "$REPOSITORY:$VERSION"
