---
name: Build docker image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-docker-image.yml
      - Containerfile
      - files/**
      - scripts/*
  pull_request:
    paths:
      - .github/workflows/build-docker-image.yml
      - Containerfile
      - files/**
      - scripts/*

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ceph_version:
          - nautilus
          - octopus
          - pacific
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup docker
        uses: docker/setup-buildx-action@v1

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Build docker image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.ceph_version }}
          REPOSITORY: osism/cephclient

      - name: Push docker image
        run: |
          scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.ceph_version }}
          REPOSITORY: osism/cephclient
        if: github.ref == 'refs/heads/main'
