---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - scripts/*
  pull_request:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - scripts/*

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ceph_version:
          - nautilus
          - octopus
          - pacific
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.ceph_version }}
          REPOSITORY: osism/cephclient

      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          VERSION: ${{ matrix.ceph_version }}
          REPOSITORY: osism/cephclient
        if: |
          github.repository == 'osism/container-image-cephclient' &&
          github.ref == 'refs/heads/main'
